"""
AI 이미지 생성 (DALL-E / Stable Diffusion)

AI를 통해 슬라이드에 사용할 이미지를 생성합니다.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

from ...utils.logger import get_logger

logger = get_logger("ai_image_generator")


class AIImageGenerator:
    """
    AI 이미지 생성기

    OpenAI DALL-E 또는 Stability AI를 사용합니다.
    API 키가 없으면 비활성화됩니다.
    """

    def __init__(self, cache_dir: Optional[Path] = None):
        self.cache_dir = cache_dir or Path("output/.image_cache/ai")
        self.cache_dir.mkdir(parents=True, exist_ok=True)

        self.openai_key = os.getenv("OPENAI_API_KEY", "")
        self.stability_key = os.getenv("STABILITY_API_KEY", "")

    async def search(self, request) -> "ImageResult":
        """
        AI 이미지 생성

        Args:
            request: ImageRequest

        Returns:
            ImageResult
        """
        from ..manager import ImageResult

        if not self.openai_key and not self.stability_key:
            return ImageResult(
                placeholder_id=request.placeholder_id,
                success=False,
                error="AI 이미지 생성 API 키 미설정",
            )

        # DALL-E 시도
        if self.openai_key:
            result = await self._generate_dalle(request)
            if result and result.success:
                return result

        return ImageResult(
            placeholder_id=request.placeholder_id,
            success=False,
            error="AI 이미지 생성 실패",
        )

    async def _generate_dalle(self, request):
        """DALL-E API로 이미지 생성"""
        from ..manager import ImageResult

        try:
            import openai
            client = openai.OpenAI(api_key=self.openai_key)

            prompt = self._build_prompt(request)

            response = client.images.generate(
                model="dall-e-3",
                prompt=prompt,
                size="1792x1024",
                quality="standard",
                n=1,
            )

            image_url = response.data[0].url

            # 다운로드
            import urllib.request
            file_path = self.cache_dir / f"{request.placeholder_id}.png"
            urllib.request.urlretrieve(image_url, str(file_path))

            return ImageResult(
                placeholder_id=request.placeholder_id,
                file_path=file_path,
                source="dalle",
                attribution="Generated by DALL-E 3",
                success=True,
            )

        except Exception as e:
            logger.warning(f"DALL-E 생성 실패: {e}")
            return None

    def _build_prompt(self, request) -> str:
        """이미지 생성 프롬프트 구성"""
        base = request.description or " ".join(request.keywords)

        if request.category == "diagram":
            return f"Professional business diagram, clean minimal style: {base}"
        elif request.category == "illustration":
            return f"Professional illustration, modern style: {base}"
        else:
            return f"Professional photograph, high quality, business presentation style: {base}"
